### ISSUE TITLE
Сайт

### ISSUE THREAD

**Issue by mates4352** [vadim-m/petcare#11]
Не соответствие по макету 
![Screenshot_1](https://github.com/vadim-m/petcare/assets/74828644/a031fdf8-990d-44ae-88ed-70041506acb9)
![Screenshot_2](https://github.com/vadim-m/petcare/assets/74828644/70f38915-35f7-482f-811a-b2981f13a943)

Размер padding маленький
![Screenshot_3](https://github.com/vadim-m/petcare/assets/74828644/65f7ecd9-8bcf-4115-9e95-01e42acde55f)

По остальному визуалу все хорошо

**Comment by vadim-m** [comment]
Добрый день,

По первому пункту - я подумал, что это именно фишка слайдера, который имеет особую закругленную форму, поэтому я наложил этот полукруг сверху.  Просто слайда с собакой в потоке макета не было, поэтому я решил, что он должен выглядеть аналогично первому (ну переделать там в пару CSS правил).

По второму пункту - так как варианта было только 2 - desktop и mobile, делал промежуточные точки сам,  с компа этот момент упустил.

Спасибо за обратную связь!
